# Generated by Django 3.1 on 2022-06-25 17:43

from django.db import migrations
import django.db.models.deletion
import django_boost.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentprocess',
            name='id',
        ),
        migrations.AddField(
            model_name='employmentprocess',
            name='application',
            field=django_boost.models.fields.AutoOneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employment_process', serialize=False, to='jobs.application'),
            preserve_default=False,
        ),
    ]
